---
- name: Include Git setup tasks
  include_tasks: git_setup.yml

- name: Include SSH setup tasks
  include_tasks: ssh_setup.yml

- name: Update .bashrc with git branch colors and aliases
  blockinfile:
    path: "~/.bashrc"
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e "/^[^*]/d" -e "s/* \(.*\)/(\1)/"
      }
      export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "
      alias gst="git status"
      alias god="git log --graph --oneline --decorate"
      alias gb="git branch"
      alias ga="git add"
      alias gc="git commit"
      alias gp="git push"
      alias gpl="git pull"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GIT BRANCH COLORS & aliases"
  become: false
