---
- name: Create ~/.ssh directory
  file:
    path: "~/.ssh"
    state: directory
    mode: '0700'
  become: no

- name: Generate SSH key if it does not exist
  openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: "{{ ssh_key_type }}"
    comment: "{{ git_email }}"
  become: no

- name: Display public SSH key
  command: cat "{{ ssh_key_path }}.pub"
  register: ssh_public_key
  changed_when: false
  become: no

- name: Show SSH public key
  debug:
    msg: "{{ ssh_public_key.stdout }}"
