# roles/jenkins/tasks/main.yml
---
- name: Pull Jenkins Docker image
  docker_image:
    name: "{{ jenkins_image.split(':')[0] }}"
    tag: "{{ jenkins_image.split(':')[1] | default('latest') }}"
    source: pull

- name: Create Jenkins home directory with proper permissions
  file:
    path: "{{ jenkins_home }}"
    state: directory
    mode: '0750'
    owner: "{{ jenkins_user_uid }}"
    group: "{{ jenkins_user_gid }}"

- name: Run Jenkins container
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ jenkins_http_port }}:8080"
    volumes:
      - "{{ jenkins_home }}:{{ jenkins_home }}"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"

- name: Wait for Jenkins HTTP service to be up
  uri:
    url: "http://localhost:{{ jenkins_http_port }}/login"
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 30
  delay: 10
  ignore_errors: yes

- name: Check if initial admin password exists
  stat:
    path: "{{ jenkins_home }}/secrets/initialAdminPassword"
  register: admin_password_file
  ignore_errors: yes

- name: Display initial admin password if available
  block:
    - name: Get initial admin password
      command: "cat {{ jenkins_home }}/secrets/initialAdminPassword"
      register: jenkins_admin_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"
  when: admin_password_file.stat.exists | default(false)

- name: Check Jenkins installation status
  debug:
    msg: >
      Jenkins is running at http://{{ ansible_host }}:{{ jenkins_http_port }}
      {% if admin_password_file.stat.exists | default(false) %}
      This appears to be a new installation. Use the initial admin password displayed above to set up Jenkins.
      {% else %}
      This appears to be an existing Jenkins installation that has already been set up.
      {% endif %}
