---
- name: Include system update tasks
  include_tasks: system_update.yml

- name: Install basic packages
  apt:
    name:
      - git
      - vim
      - openssh-server
      - openssh-client
      - curl
      - build-essential
      - ca-certificates
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-venv
      - htop
      - fontconfig
      - openjdk-17-jre
      - net-tools
    state: present

- name: Clean up unnecessary packages
  apt:
    autoremove: yes
