---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Perform dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
